feat: added steps to code_format job

diff --git a/.github/workflows/build_and_mirror.yml b/.github/workflows/build_and_mirror.yml
--- a/.github/workflows/build_and_mirror.yml
+++ b/.github/workflows/build_and_mirror.yml
@@ -25,16 +25,19 @@ jobs:
 
   code_format:
     name: Check code formatting
-    run: |
-      `./tests/format-code.sh`
-      STATUS=$?
-      
-      if [ $STATUS -gt 0 ]; then
-        echo "Error! Code isn't formatted"
-        exit 1
-      fi
-      echo "Success! Code is correctly formatted"
-      exit 0
+    runs-on: ubuntu-latest
+    steps:
+      - name: Run check format script
+        run: |
+          `./tests/format-code.sh`
+          STATUS=$?
+          
+          if [ $STATUS -gt 0 ]; then
+            echo "Error! Code isn't formatted"
+            exit 1
+          fi
+          echo "Success! Code is correctly formatted"
+          exit 0
 
 
   mirroring_to_github:
