feat: added clang format to workflow

diff --git a/.github/workflows/build_and_mirror.yml b/.github/workflows/build_and_mirror.yml
--- a/.github/workflows/build_and_mirror.yml
+++ b/.github/workflows/build_and_mirror.yml
@@ -7,7 +7,7 @@ env:
 
 jobs:
   build:
-    name: "build with cmake"
+    name: Build project with cmake
     runs-on: ubuntu-latest
     steps:
       - name: Install low-level dependency libxrandr
@@ -22,11 +22,22 @@ jobs:
       - name: Build the project
         run: cmake --build build
 
-      # - name: List files
-      #   run: ls
+      - name: Format code using clang-format
+        run: |
+          `./tests/format-code.sh`
+          STATUS=$?
+          
+          if [ $STATUS -gt 0 ]; then
+            echo "Error! Code isn't formatted"
+            exit 1
+          fi
+          echo "Success! Code is correctly formatted"
+          exti 0
+
+
   mirroring_to_github:
-    needs: build
-    name: "Push the current commit to github"
+    needs: format_code
+    name: Push the current commit to github
     runs-on: ubuntu-latest
     steps:                                              # <-- must use actions/checkout before mirroring!
       - uses: actions/checkout@v3
